version: '2'

services:
  db:
    image: postgres:9.6
    env_file: ../config/envs/dev-docker.env
    volumes:
      - /etc/postgresql
      - /var/log/postgresql
      - /var/lib/postgresql
    ports:
      - '5433:5432'
  app:
    build: app
    env_file: ../config/envs/dev-docker.env
    environment:
      - DOCKER=1
    volumes:
      - ..:/app
    links:
      - db
    ports:
      - '8080:8080'
    command: ["start"]
